### ISSUE TITLE
[FEATURE] Add TIME TAKEN in RESULTS page

### ISSUE THREAD

**Issue by prakhartiwari0** [prakhartiwari0/Arito#10]
**Is your feature request related to a problem? Please describe.**
When we give tests, it is good to get the data of how much time was consumed so that we can get an estimate of our skill level and can improve upon that.

**Describe the solution you'd like**
We can use some time functions in JavaScript and start the time at the start of the test, and end it when the test ends. 

It would be great if we could show 2 things - 
- Time taken for the whole test
- Average time taken to answer each question

We can calculate this data using mathematics!

**Comment by jia-ayo** [comment]
the retake button is not working after the result is shown

**Comment by prakhartiwari0** [comment]
> the retake button is not working after the result is shown

I know, it is a dummy button as of now, we need to add the functionality
