### ISSUE TITLE
[IMPROVEMENT] Adding a footer  

### ISSUE THREAD

**Issue by nishita2104** [prakhartiwari0/Arito#100]
## What improvement are you suggesting?
Adding a footer to incorporate all the links mentioned in the site will give it an organised look.

## Why should make this improvement?
The website will look more organised and will become more appealing.

## How can we make these improvements?
We take the mentioned links and add a horizontal footer to incorporate them all.

## Additional Context
![image](https://github.com/prakhartiwari0/Arito/assets/98174888/f1212664-3176-48b7-a111-bd9bd2b41a48)

**Comment by prakhartiwari0** [comment]
The nature of this app doesn't require a footer, it's mainly for kids and they don't care for the footer.

Happy Contributing
