### ISSUE TITLE
Improve the UI of the project

### ISSUE THREAD

**Issue by sumitkr2000** [prakhartiwari0/Arito#101]
## What improvement are you suggesting?
Hey, @prakhartiwari0 I want to improve the UI of the project a little bit so that it looks clean. For now, it is looking somewhat cluttered. Please assign me this issue. Thank you!

## Why should make this improvement?
Improving the font and styles of the button. Add a footer and Header.

## How can we make these improvements?
Describe the process or the changes we should do to make these improvements

## Additional Context
Write if you have anything more to say, or if you want to add screenshots, links, or videos.

**Comment by prakhartiwari0** [comment]
Please describe what exactly you want to do @sumitkr2000. This is not the right way to raise an issue.
Thank you

**Comment by sumitkr2000** [comment]
I want to improve the fonts button and add a footer and header to the website @prakhartiwari0

**Comment by prakhartiwari0** [comment]
Fonts are already there, what to improve with that?
And there if no footer required in this project if you have read some previous issues, also what exactly do you mean by header?
I think all of that is either not required or already present. Most parts of the App don't require major layout changes. 

I hope I was able to explain @sumitkr2000 
If you have any other specific points or wanna describe exactly what is in your mind to improve those stuff, then please go ahead and share it.

Happy Contributing!

**Comment by sumitkr2000** [comment]
So you tell me what can I improve in the website?

**Comment by prakhartiwari0** [comment]
There is always a scope for improvement, but I don't think this is the right way to contribute. You should have raised an issue only after figuring out what exactly can be improved, why it should be done, and what its effects will be. I encourage you to analyse the project more and more, understand its nature of it, and then try to target a specific issue. And when you raise an issue, you should be absolutely clear about what to do, and describe that thoroughly in the template.

Happy Contributing!
