### ISSUE TITLE
Adding Highest Score [IMPROVEMENT] 

### ISSUE THREAD

**Issue by Anikinee** [prakhartiwari0/Arito#102]
## What improvement are you suggesting?
There must a button such as "SAVE RESULT" for saving the results of the test.

## Why should make this improvement?
This improvement is required as when we try to take a new test the results of the previous test gets lost

## How can we make these improvements?
I can do this by adding a new button to save the result.

Please assign it to me under GSSoC-23.

**Comment by prakhartiwari0** [comment]
And how are you gonna save them? I mean what format will be there? @Anikinee Please describe

**Comment by Anikinee** [comment]
> And how are you gonna save them? I mean what format will be there? @Anikinee Please describe

I want to create a button "Save result" and upon clicking that button a pdf file containing the scores will be downloaded in the user's local storage so that even if the user takes other test but he/she can download the scores.

**Comment by prakhartiwari0** [comment]
What will you use to make that pdf? @Anikinee Can you explain the process? I need to inform you that no npm packages are meant to be used in this project.

**Comment by Anikinee** [comment]
> What will you use to make that pdf? @Anikinee Can you explain the process? I need to inform you that no npm packages are meant to be used in this project.

I shall use the jsPDF and html2canvas library.

**Comment by prakhartiwari0** [comment]
Nope, those are npm packages only. If you have any other option that would be great! @Anikinee 
This project is meant to use only Vanilla Javascript without any frameworks, packages, etc.

**Comment by Anikinee** [comment]
> Nope, those are npm packages only. If you have any other option that would be great! @Anikinee This project is meant to use only Vanilla Javascript without any frameworks, packages, etc.

Right now, I don't have any other option. But, can I add a feature of highest score which will show the highest score out of all the retests the user takes. Whenever the user will opt for new test then it will be refreshed. 
If possible please assign me this.

**Comment by prakhartiwari0** [comment]
Hello @Anikinee, it is not a good practice to change the title of the issue after a discussion and pivot to another issue altogether. You should raise a new issue describing what exactly should be done, why and what will be the benefits of it. 

Also, I would highly recommend you first learn about Open Source, Git &GitHub, and the best practices to be followed while contributing. You can [watch this video by Eddie on FreeCodeCamp](https://www.youtube.com/watch?v=yzeVMecydCE) to get a good idea of everything. 
After learning about it well, you can actually contribute to the project and help make it better!

Happy Contributing!
