### ISSUE TITLE
Adding footer[FEATURE] 

### ISSUE THREAD

**Issue by Anikinee** [prakhartiwari0/Arito#104]
**Is your feature request related to a problem? Please describe.**
There must a footer included in this project.

**Describe the solution you'd like**
A footer containing the link of different social media handles so that the user can connect to the author, and button to move to the beginning of the page. Also, I can add anything more in the footer section if you suggest.

Please assign it to me under GSSOC'23.

**Comment by vikasjain2003** [comment]
Hii author please assign and add me too to collaborate and add the footer in the site.
Please assign it to me under GSSOC'23.

**Comment by prakhartiwari0** [comment]
@vikasjain2003 @Anikinee 
There was already an issue about this and it's closed because this is not needed. Please read #100 once. And from the future, kindly search in the issues if something related to your issue was/is already there. 

Thank you & Happy Contributing!
