### ISSUE TITLE
Adding Power and Square root features[FEATURE] 

### ISSUE THREAD

**Issue by SasiVardhan247** [prakhartiwari0/Arito#105]
**Is your feature request related to a problem? Please describe.**
Apart from addition, and subtraction we can add features like finding the power of a number and square root which helps in improving cognitive skills in kids.

**Describe the solution you'd like**
As we have done addition and subtraction we can also add similar functionality to power and square root

**Describe alternatives you've considered**
It's straight forward implementation.

**Additional context**
![image](https://github.com/prakhartiwari0/Arito/assets/83742554/133001a9-f78e-46d7-b091-eee7d1c4fa48)

**Comment by prakhartiwari0** [comment]
Please go read #6 Discussion. And I would suggest exploring the repository completely before actually doing anything. Happy Contributing @SasiVardhan247
