### ISSUE TITLE
[IMPROVEMENT] Signup/in feactur. login form

### ISSUE THREAD

**Issue by anshita742** [prakhartiwari0/Arito#109]
Hi there! I am selected as GSSOC contributor and your tech stack matches mine so I would like to be a part of this project ⭐

**Comment by prakhartiwari0** [comment]
Hello @anshita742 
I would recommend you first learn about Open Source, Git &GitHub, and the best practices to be followed while contributing. You can [watch this video by Eddie on FreeCodeCamp](https://www.youtube.com/watch?v=yzeVMecydCE) to get a good idea of everything. 
After learning about it well, you can actually contribute to the project and help make it better!

Happy Contributing!
