### ISSUE TITLE
Contact us section

### ISSUE THREAD

**Issue by Aarushijain-06** [prakhartiwari0/Arito#111]
Dear @prakhartiwari0  ,
I hope this message finds you well. I want to request the addition of the Contact page to your repository, it will help the users to get connected with us. Please assign me this issue😊

**Comment by prakhartiwari0** [comment]
Hello @Aarushijain-06, 
There already are sufficient links to contact the maintainers of the project, as you can see in this image
![image](https://github.com/prakhartiwari0/Arito/assets/65062036/734a93a7-9eab-4a60-8d9c-682f76d66abd)


If you have any other points to add then please tell me, if they are good I will reopen the issue.

Also, I would highly recommend you first learn about Open Source, Git &GitHub, and the best practices to be followed while contributing. You can [watch this video by Eddie on FreeCodeCamp](https://www.youtube.com/watch?v=yzeVMecydCE) to get a good idea of everything. 
After learning about it well, you can actually contribute to the project and help make it better!

Happy Contributing!
