### ISSUE TITLE
Adding a navbar for improvement 

### ISSUE THREAD

**Issue by Medhanshverma** [prakhartiwari0/Arito#114]
## What improvement are you suggesting?
Adding a navbar to a website offers several benefits. It enhances navigation, improves user experience, increases engagement, ensures mobile responsiveness, and contributes to branding and aesthetics. A well-designed and intuitive navbar simplifies website navigation, allowing users to easily access important sections. It also promotes exploration of content, particularly on mobile devices, creating a positive impression and reinforcing brand identity.

## Why should make this improvement?
Adding a navbar is a beneficial improvement for several reasons. It enhances website navigation by providing a clear and organized menu structure, allowing users to easily find and access different sections of your site. This improvement improves user experience by reducing friction and making it easier for visitors to engage with your content. Additionally, a well-designed navbar can create a more professional and visually appealing website, reinforcing your brand identity and making a positive impression on users.

## How can we make these improvements?
To make these improvements, design a clear and organized layout for the navbar. Establish a logical navigation hierarchy, ensure responsiveness for different screen sizes, and incorporate a visually appealing design that aligns with your brand identity.

**Comment by Medhanshverma** [comment]
Assign me this issue for GSSOC'2023

**Comment by Iamdivyak** [comment]
I would like to work with this issue. please assign me under gssoc contributor

**Comment by prakhartiwari0** [comment]
Hello @Medhanshverma, it's good to see that you want to contribute to the project.
The thing is, the layout and design of this app don't require any navbar, we don't have to treat it as other websites, it's for kids, and we don't have a number of pages of content that needs to be divided in the navbar. There are a handful of links, which are properly listed on the homepage. If you can improve that in a specific way, do share your points or raise a new issue.

Also, I would highly recommend you first learn about Open Source, Git &GitHub, and the best practices to be followed while contributing. You can [watch this video by Eddie on FreeCodeCamp](https://www.youtube.com/watch?v=yzeVMecydCE) to get a good idea of everything. 
After learning about it well, you can actually contribute to the project and help make it better!

Happy Contributing!
