### ISSUE TITLE
Add a certificate

### ISSUE THREAD

**Issue by Durgesh4993** [prakhartiwari0/Arito#115]
With the help of google cloud i'll created an auto generated certificate after giving a test this certificate will be generated

**Comment by Abhinavcode13** [comment]
assign this issue to me @prakhartiwari0 .

**Comment by prakhartiwari0** [comment]
Hello @Durgesh4993, 
Currently, this app is not having any backend or any plans for it, therefore we can't proceed with this issue. Maybe you can find something else to improve the project

Also, I would highly recommend you first learn about Open Source, Git &GitHub, and the best practices to be followed while contributing. You can [watch this video by Eddie on FreeCodeCamp](https://www.youtube.com/watch?v=yzeVMecydCE) to get a good idea of everything. 
After learning about it well, you can actually contribute to the project and help make it better!

Happy Contributing!

**Comment by Durgesh4993** [comment]
@prakhartiwari0 Are you crazy man i have already mentioned i'll be use the google cloud and you suggesting me a vedio for learn how to contribute. I have more then 1 year of experience in open source development.

**Comment by Abhinavcode13** [comment]
@Durgesh4993 leave brother , just a avg project admin.
