### ISSUE TITLE
[FEATURE] Add the social media handles at footer.

### ISSUE THREAD

**Issue by Abhinavcode13** [prakhartiwari0/Arito#117]
->Determine which social media platform you want to include (e.g., Twitter, GitHub, LinkedIn).
->Add a short description next to the social media handle to indicate what it represents.

Above implementations will be done to index.html page

please assign me this issue under Gssoc 23 @prakhartiwari0 

Thanks and regards
Abhinav Kumar

**Comment by purviporwal0** [comment]
I would love to contribute to this feature

**Comment by DhairyaMajmudar** [comment]
I would love to contribute to this project under GSSoC'23 if you assign this issue to me. I know some good enough resources from which I can add icons of social media sites.

**Comment by prakhartiwari0** [comment]
Hello @Abhinavcode13, it's good to see you want to contribute to the project.
However, I want to point out that there are already social links present on the homepage, and multiple of them is not needed. 

![image](https://github.com/prakhartiwari0/Arito/assets/65062036/9e2f1f76-5c0e-4af3-bb9d-06daea1810cd)


@DhairyaMajmudar @purviporwal0 @Abhinavcode13 
Also, I would highly recommend you first learn about Open Source, Git &GitHub, and the best practices to be followed while contributing. You can [watch this video by Eddie on FreeCodeCamp](https://www.youtube.com/watch?v=yzeVMecydCE) to get a good idea of everything. 
After learning about it well, you can actually contribute to the project and help make it better!

Happy Contributing!
