### ISSUE TITLE
Learning resources

### ISSUE THREAD

**Issue by Suchitra-Sahoo** [prakhartiwari0/Arito#119]
Provide additional resources like tutorials, tips, tricks to master arithmetic concepts. Include visual aids, diagrams to make learning more engaging.

allow me to work on this idea under GSoc'23

**Comment by prakhartiwari0** [comment]
Hey @Suchitra-Sahoo, good to see you want to contribute to the project.
I would suggest you read discussion #84, we have already talked about why it is NOT a good idea to add the learning content in the app. 

Also, I would highly recommend you first learn about Open Source, Git &GitHub, and the best practices to be followed while contributing. You can [watch this video by Eddie on FreeCodeCamp](https://www.youtube.com/watch?v=yzeVMecydCE) to get a good idea of everything. 
After learning about it well, you can actually contribute to the project and help make it better!

Happy Contributing!
