### ISSUE TITLE
[Improvement] Improve the Contributing.md

### ISSUE THREAD

**Issue by prakhartiwari0** [prakhartiwari0/Arito#12]
## [Contributing Guidelines](https://github.com/prakhartiwari0/Arito/blob/main/CONTRIBUTING.md#contributing-guidelines)

It needs a lot of changes in terms of beautification, information, language improvements, and more.

### Sections to add:
- **Guidelines:** This will contain all the guidelines for contributing to the project
- **Pull Requests Review Criteria**
- **Other points to remember while submitting your work**(optional)
- **Resources** 

Or any other helpful section

**Comment by EmmanuelEngelbert** [comment]
Hi @prakhartiwari0 I believe the Contributing.md file could benefit from having instructions on how to complete pull requests via the browser. The EddieHub Community has a good example of what I am talking about here https://github.com/EddieHubCommunity/hacktoberfest-practice. Let me know what you think. Thank you!

**Comment by prakhartiwari0** [comment]
Um yeah @EmmanuelEngelbert that is also a good thing to add, I will copy-paste the steps with some editing (because anyways it will be the same) to our Contributing.md. Thanks for your suggestion!

**Comment by aswin2108** [comment]
@prakhartiwari0 I would love to work on this! I found some missing Infos and could correct, add and refactor it. 
Could you assign this to me?

**Comment by prakhartiwari0** [comment]
Sure @aswin2108 
Go ahead!

**Comment by Jiya55** [comment]
Hi, I want to become a part of this project but this is my first open source project so i don't know how to go about it. Could I be of help with something? I know basic html and css, a bit of JS and i learnt Django(python web framework) a while back.

**Comment by prakhartiwari0** [comment]
Hey @Jiya55, it's great that you are starting your Open Source journey, feel free to ask questions or if you need any help with this.
I know starting could be a little hard as in Open source we need to find issues which we are capable of solving and then work on them. You can explore the existing unassigned issues and see if you can work on any of them. You can also take time to use the app on your devices and try to find any bug in the app, and then raise an issue for that (do check if a similar issue is already there or not) and if you can, then start working on the solution!

The Javascript used in this app is very basic and beginners like you can easily understand it, just give it some time to it.

Also, if you haven't learned Git & Github, I would highly recommend you do so, as they are important skills and you cannot work without them in Open Source. The Basics are enough and you will learn during the process so don't go too deep at the starting.

I hope I was able to help, as said earlier,  feel free to ask questions or if you need any help with this.

Happy Contributing!

**Comment by Jiya55** [comment]
Ok, thanks for your reply.

**Comment by Somya-Singhal** [comment]
Hi @prakhartiwari0 
Is this issue still open to work on? I am a GSSoC'23 contributor and want to contribute to this repo.

**Comment by bhaktisharma26** [comment]
Hi @prakhartiwari0 would like to work on this issue if it is still open. Thankyou.

**Comment by prakhartiwari0** [comment]
Hello @Somya-Singhal @bhaktisharma26, it's good to see you want to contribute to the project.
This issue is basically for all the PRs that improve `Contributing.md`, currently, it isn't having any specific tasks to do, so I think it's better to close it to prevent further confusion. 

Also, I would highly recommend you all first learn about Open Source, Git &GitHub, and the best practices to be followed while contributing. You can [watch this video by Eddie on FreeCodeCamp](https://www.youtube.com/watch?v=yzeVMecydCE) to get a good idea of everything. 
After learning about it well, you can actually contribute to the project and help make it better!

Happy Contributing!
