### ISSUE TITLE
[IMPROVEMENT] : Add Back Button [GSSOC'23]

### ISSUE THREAD

**Issue by Pragati-3003** [prakhartiwari0/Arito#120]
I would like to add the button which redirect you to the main page when you start practicing. 
![IMG_20230521_201937](https://github.com/prakhartiwari0/Arito/assets/132778037/a0b8b0b8-b357-45ef-9e74-6503b614ab07)
I would add a button at the top - left side of the page. 
So, please assign this issue to me under GSSOC'23. 
Thanking you.

**Comment by prakhartiwari0** [comment]
Hello @Pragati-3003,  it's good to see you want to contribute to the project.
There is already issue #107 which aims to do the same. If you can help the already assigned person, or simply share your suggestions in the discussion there, it would be good.

Happy Contributing!
