### ISSUE TITLE
will be improving up the UI of page slider in right side . 

### ISSUE THREAD

**Issue by abhay-raj19** [prakhartiwari0/Arito#121]
will be improving up the right slider that shows up the progress of the page length and will also add up a page slider that navigates to the top of the page.
And will also improving up the UI that is not matching up with the website.

Pls do assign me for the best results.

**Comment by prakhartiwari0** [comment]
Hello @abhay-raj19  it's good to see you want to contribute to the project.
However, I can't understand what you want to do, the page slider you are talking about is basically a scrollbar, which we styled according to our theme. If you find any issue with that, please raise a new issue specifically targeting the problem, and properly mention all the details.

Also, I would highly recommend you first learn about Open Source, Git &GitHub, and the best practices to be followed while contributing. You can [watch this video by Eddie on FreeCodeCamp](https://www.youtube.com/watch?v=yzeVMecydCE) to get a good idea of everything. 
After learning about it well, you can actually contribute to the project and help make it better!

Happy Contributing!

**Comment by prakhartiwari0** [comment]
If you think I am unable to understand your points, please describe more with images, and the issue maybe reopened if it's something to work on.
