### ISSUE TITLE
[FEATURE] Restart button

### ISSUE THREAD

**Issue by deveshidwivedi** [prakhartiwari0/Arito#122]
There should be a restart test button while the user is attempting problems so that one can always restart if they need to or wish to. If there exists a restart button while problems are being attempted then it'll only be better. It is a basic feature and can be in function very well.

**Comment by deveshidwivedi** [comment]
please assign it to me under GSSoC'23.

**Comment by prakhartiwari0** [comment]
Hello @deveshidwivedi  it's good to see you want to contribute to the project. 
 I am unable to understand clearly, I want to know if the button will be reloading the page or do something else. Please describe more about the functionality of the button and why & how to implement it.

Also, I would highly recommend you first learn about Open Source, Git &GitHub, and the best practices to be followed while contributing. You can [watch this video by Eddie on FreeCodeCamp](https://www.youtube.com/watch?v=yzeVMecydCE) to get a good idea of everything. 
After learning about it well, you can actually contribute to the project and help make it better!

Happy Contributing!

**Comment by gambhirsharma** [comment]
Hey, @deveshidwivedi do you want to work on this issue?

I am temporarily closing this issue. If you want to work on this issue reopen it and start contributing.
