### ISSUE TITLE
[FEATURE] Option for Timer

### ISSUE THREAD

**Issue by kailashchoudhary11** [prakhartiwari0/Arito#123]
**Is your feature request related to a problem? Please describe.**
We can provide an option to set up a timer before starting the quiz.
The quiz will be automatically submitted once the time is over.
The feature can be option same as the negative marking feature.
The timer will be visible to the user while attempting the test.

**Comment by prakhartiwari0** [comment]
How do you plan to approach the implementation of this feature? Can you also describe all the UI and functionality changes that will be required to do so :) @kailashchoudhary11

**Comment by gambhirsharma** [comment]
Hey, @kailashchoudhary11 do you want to work on this issue?

If yes then explain to us in detail how you will implement this feature and also provide some design prototypes. 

For now, I am temporarily closing this issue. If you want to work on this issue reopen it and start contributing.
