### ISSUE TITLE
[FEATURE] Add Sound/Music/Volume Buttons

### ISSUE THREAD

**Issue by prakhartiwari0** [prakhartiwari0/Arito#13]
**Is your feature request related to a problem? Please describe.**
Sometimes we want to stop the background music or the sounds of button clicks of the app but not decrease the volume of our device. This leads to irritation because there is no option for mute/unmute sounds or volume control in the app itself

**Describe the solution you'd like**
It would be handy if the app itself contains buttons to disable/enable music/sounds. 
Adding a volume control button will also be good.

**Additional context**
| ![image](https://user-images.githubusercontent.com/65062036/202833692-aae81761-bfdf-41c5-b5ff-4d82808ea50e.png) | <img src="https://previews.123rf.com/images/auttkhamkhauncham/auttkhamkhauncham1412/auttkhamkhauncham141200106/34350188-sound-off-and-sound-on.jpg" width="20%"> |
| --- | --- |

**Comment by Daniel53245** [comment]
Hi I think I could help with adding a slide bar in the webpage for volume control

**Comment by prakhartiwari0** [comment]
> Hi I think I could help with adding a slide bar in the webpage for volume control

Sure go ahead, and try it out if you can, however, I would like you to first figure out the enable & disable music buttons because that is more important
