### ISSUE TITLE
[FEATURE] Share the result with friends 

### ISSUE THREAD

**Issue by KeplerInCoding** [prakhartiwari0/Arito#133]
sharing the results foster the healthy competition among children and makes learning more enjoying and fruitful.

**Describe the solution you'd like**
i would love to add a "share your results" feature on result page where the percentage, difficulty level, negative marking, time taken is shared in a very engaging and interactive manner tempting more kids to take up the challenge.

**Describe alternatives you've considered**
we can share the website link along with the kids result so that anyone can get redirected, this would help in promoting the site

**Additional context**
i want you to assign me this responsibility, i would love to add some cool features to this wonderful project !!

**Comment by prakhartiwari0** [comment]
Please describe what exactly can be done & how, I will reopen the issue if it seems good :)


Happy Contributing!
