### ISSUE TITLE
Remove sound label after test completion

### ISSUE THREAD

**Issue by hindu-muppala** [prakhartiwari0/Arito#134]
## What improvement are you suggesting?
Remove sound html after test completion or add sound after testing

## Why should make this improvement?
I observed the sound is not coming after completing test. So I will try to add sound. If it is not possible, I will remove the sound html 
## How can we make these improvements?
I will just remove this html code after button is submitted or add sound.
## Additional Context
![image](https://github.com/prakhartiwari0/Arito/assets/120579608/a737ebd3-3bbf-4d8c-8a9f-820530d82efc)

**Comment by prakhartiwari0** [comment]
Hey @hindu-muppala, I think this is an unnecessary addition, the volume slider is at the bottom and doesn't spoil the UI/UX. If you have anymore suggestions or points please share them.

Happy Contributing
