### ISSUE TITLE
[FEATURE] #GSSoC'23 Add Progress Tracker

### ISSUE THREAD

**Issue by Grogu22** [prakhartiwari0/Arito#135]
**Is your feature request related to a problem? Please describe.**
When we `retake` a test or go 'back to homepage` a new instance of a user is created, we have to add our names, the arithmetic operation, question difficulty, etc.. and our progress is not saved. 
 
**Describe the solution you'd like**
 Would be great if we could have a progress tracker that saves changes until we close the tab in our browser.

**Describe alternatives you've considered**
Add a **progress tracker** in a json file or as a js object

[//]: # (**Additional context**)
[//]: # (Add any other context or screenshots about the feature request here.)

**Comment by prakhartiwari0** [comment]
> When we retake a test or go 'back to homepage` a new instance of a user is created, we have to add our names, the arithmetic operation, question difficulty, etc.. and our progress is not saved.

Can you please describe the actual issue? I am unable to understand "new instance of a user", and the progress will be having what if the questions are of different properties? 

Please explain clearly, if this looks I will reopen the issue, no problem.

Happy Contributing!
