### ISSUE TITLE
[BUG] Cursor Not changing when Hovered on Buttons

### ISSUE THREAD

**Issue by gurmehakk20** [prakhartiwari0/Arito#136]
## What improvement are you suggesting?
Tell us what improvement(s) are you thinking about for this project.
there is a small problem in CSS of main.html page, the cursor is changing to pointer while going  on label in form_element div instead it should be on input... on clicking the buttons, the cursor remains the same 

## Why should make this improvement?
Tell us the reasons why we should make these improvements, what will be the outcome?
I would like to quote "continuous improvements lead to success", even if small.

## How can we make these improvements?
Describe the process or the changes we should do to make these improvements
remove cursor: pointer from .form_element label 

## Additional Context
Write if you have anything more to say, or if you want to add screenshots, links, or videos.

**Comment by gambhirsharma** [comment]
@gurmehakk20 same issue has been raised in #130 

You can check #130 and get more details. 

For now, I am temporarily closing this issue.
