### ISSUE TITLE
[FEATURE] timer 

### ISSUE THREAD

**Issue by gurmehakk20** [prakhartiwari0/Arito#137]
**Is your feature request related to a problem? Please describe.**
I think there should be timer while attempting the questions. It could have been a cute clock or a digit countdown. But, I think since this web application is for kids, countdown timer will be preferrable.

**Describe the solution you'd like**
It could be made using js

**Comment by shwetazade27** [comment]
I would like to work on this feature (Gssoc'23)

**Comment by gambhirsharma** [comment]
@gurmehakk20 are you working on this issue or should I assign @shwetazade27 to this issue?

**Comment by gambhirsharma** [comment]
I guess no one is interested in this issue. So I am closing this issue.
