### ISSUE TITLE
[IMPROVEMENT] 

### ISSUE THREAD

**Issue by shwetazade27** [prakhartiwari0/Arito#141]
## What improvement are you suggesting?
Celebrating Emoji, star emoji can be added according to score on displaying result.

## Why should make this improvement?
Since the app is for kids , it will make them happy on receiving stars or some cheerful emojis.

**Comment by gambhirsharma** [comment]
Hey, @shwetazade27 do you want to work on this issue?

If yes then explain to us in detail how you will implement the feature and also provide some design prototypes.

For now, I am temporarily closing this issue. If you want to work on this issue reopen it and start contributing.
