### ISSUE TITLE
Adding a scroll-to-top button

### ISSUE THREAD

**Issue by deepeshgupta3257** [prakhartiwari0/Arito#142]
add scroll to top Button which will become easy for user to navigate to top of the page . Please assign me this issue under GSSOC'23.

**Comment by Namanbansal06** [comment]
I will love to do this task. pls assign me it under GSSOC'23

**Comment by DhairyaMajmudar** [comment]
Please assign this issue t me under GSSoC'23. I will make  a mind-blowing scroll to top button using HTML, CSS and JS

**Comment by gambhirsharma** [comment]
This issue already exists in #103 & a PR has also been raised.
