### ISSUE TITLE
[FEATURE]  Add Navigation Bar and Footer section

### ISSUE THREAD

**Issue by adarsh-1262** [prakhartiwari0/Arito#146]
As on the website there is no any Nav bar and Footer section , so i want to contribute to this project by adding these two things to your website.

Assign me this task @breck7 under GSSoC'23.

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by gambhirsharma** [comment]
I don't think this website requires a footer bcoz it's a Maths challenge game for kids and there is nothing to add in the footer section.

I am closing this issue.
