### ISSUE TITLE
[IMPROVEMENT] Change in UI and Color Schemes in the web app

### ISSUE THREAD

**Issue by Namanbansal06** [prakhartiwari0/Arito#147]
## What improvement are you suggesting?
I will make the color scheme more user friendly and make some changes in ui for better look.

**Comment by dushyant-sharma937** [comment]
Hey there, I am interested in this project's development by changing in UI and color scheme under GSSOC'23

**Comment by DeepikaChauhan09** [comment]
I would like to work on this issue. Pls assign me this issue @prakhartiwari0

**Comment by Namanbansal06** [comment]
Hey Sir
Give me any update about my issue...

**Comment by gambhirsharma** [comment]
I think the UI & colour theme is ok for a kid's math game website. 

If you want to make any specific changes then mention it below.

For now, I am closing this issue.
