### ISSUE TITLE
[BUG] Accepts empty name as input 

### ISSUE THREAD

**Issue by sahil-1729** [prakhartiwari0/arito#148]
## **Describe the bug**
Before starting the game, the game starts without taking name as input
## **To Reproduce**
Go to main page
Click on 'Let's Start'
Scroll down to 'name'
Keep name box as empty
Click 'get set go', then 'start now'.
The app continues the game without taking name as input

## **Expected behavior**
The application should have taken the user's name as input before starting the game.

## **Screenshots**
![image](https://github.com/prakhartiwari0/Arito/assets/97158384/ef73860a-a671-490c-a3f4-31682360c645)![image](https://github.com/prakhartiwari0/Arito/assets/97158384/6cc671bb-0515-4135-9dd4-c00b52a5c8f2)

**Desktop (please complete the following information):**
 - OS: WIndows
 - Browser: chrome
 - Version: 113

## **Additional context**
I can fix this by adding a check on the name and displaying an error message wherever required. Please assign this to me under GSSoC'23, as I am GSSoC'23 contributor.

**Comment by gambhirsharma** [comment]
@sahil-1729 do you want to work on this issue?

**Comment by aishaalsubaie** [comment]
can you assign me this issue @gambhirsharma
