### ISSUE TITLE
[IMPROVEMENT] HomePage Improvements

### ISSUE THREAD

**Issue by prakhartiwari0** [prakhartiwari0/Arito#15]
## What improvement are you suggesting?
We can change the text on the homepage, or add/remove links. We can also make layout changes, design or style changes to improve its looks.

## Why should make this improvement?
The homepage makes the first impression, so it should be good-looking.

**Comment by Petrosdevri** [comment]
I could help in changing background and homepage outfit using SASS. I believe it would be nice to add grey to dark grey tones or even black to dark grey shades with white letters. These are some temporary ideas, you can reply about the style you prefer.

**Comment by prakhartiwari0** [comment]
> I could help in changing background and homepage outfit using SASS. I believe it would be nice to add grey to dark grey tones or even black to dark grey shades with white letters. These are some temporary ideas, you can reply about the style you prefer.

It would be great if you could share images of your design. Keep in mind that the colors should match the theme color of the website. You can find them in the basic.css file

**Comment by Petrosdevri** [comment]
These are some images from my proposals which can be found on the source code of my fork.

![Arito - Test your Arithmetic Skills -](https://user-images.githubusercontent.com/100411628/202914693-13cba60c-a03c-4640-8faf-bbc181a63928.png)
![FireShot Capture 002 - Arito - Test your Arithmetic Skills - ](https://user-images.githubusercontent.com/100411628/202914705-44cc85ae-b745-45bf-85ec-4651ed2fe547.png)
![FireShot Capture 003 - Arito - Test your Arithmetic Skills - ](https://user-images.githubusercontent.com/100411628/202914710-79f12d4f-d1dd-480b-aea8-2b652c2c05dd.png)
![FireShot Capture 004 - Arito - Test your Arithmetic Skills - ](https://user-images.githubusercontent.com/100411628/202914718-db6e4690-f7a8-4fc0-9332-6741c7afbc5f.png)
![FireShot Capture 005 - Arito - Test your Arithmetic Skills - ](https://user-images.githubusercontent.com/100411628/202914720-6eca64df-9fbf-4a39-9c89-551dc7820d63.png)

**Comment by prakhartiwari0** [comment]
I think it is not looking user-friendly and the color combinations aren't suitable for a good UX.
If you are trying to work on colors, you should take a look at issue #20 as it aims to make the app available in dark mode.

**Comment by Petrosdevri** [comment]
I could take that as well but what would you specify about the original background?

**Comment by prakhartiwari0** [comment]
> I could take that as well but what would you specify about the original background?

We will be making changes as we move forward. I couldn't completely understand what are you asking, please explain a bit.

**Comment by Petrosdevri** [comment]
I meant that you could elaborate on what you would like to improve on the page (eg. animations, button hover colors, etc.).

Also sorry for my late reply, I had some university studies.

**Comment by prakhartiwari0** [comment]
> I meant that you could elaborate on what you would like to improve on the page (eg. animations, button hover colors, etc.).
> 
> Also sorry for my late reply, I had some university studies.

No problem, we all have some work and because of the time zone difference delay in conversation could happen.

And yeah this issue is basically for all those PRs that are related to ONLY HOME PAGE. For example, PR #16 was related to this.

**Comment by prakhartiwari0** [comment]
In the future, whenever we get any idea or want to customize or improve the homepage in anyways, this issue will be linked.
And if somebody gets any specific issue, they can create another one to tackle that particular problem.

**Comment by AnkitAnandMastery17** [comment]
Hey, is this issue still open? If yes, can you assign it to me?

**Comment by prakhartiwari0** [comment]
@AnkitAnandMastery17 Actually the homepage currently needs not to have much improvement.
You can check for other issues
Happy Contributing!
