### ISSUE TITLE
[IMPROVEMENT]  In cursor

### ISSUE THREAD

**Issue by saiful64** [prakhartiwari0/Arito#155]
## What improvement are you suggesting?
As this website is a kid friendly website I think a custom cursor should be there like a pencil or something related to the website

## Why should make this improvement?
If the cursor looks like a ruler or pencil, users will feel more connected to the content.

## How can we make these improvements?
Changing the CSS I already finished doing

## Additional Context
Please assign me this under GSSoC'23

**Comment by saiful64** [comment]
Please assign me this under GSSoC'23

**Comment by gambhirsharma** [comment]
@saiful64 can you share more detail about the new cursor design you want to implement? Also, provide a prototype/sample of the cursor design you want to add.

I am assigning this issue to you but before you start coding, provide a prototype/sample design of the cursor.

**Comment by gambhirsharma** [comment]
There is a PR #94 solving a similar issue.
