### ISSUE TITLE
Add icon for add, subtract, multiplication and division

### ISSUE THREAD

**Issue by dc9deepika** [prakhartiwari0/Arito#160]
Add icon for add, subtract, multiplication and division. it gives better user experience to kids. As it will be easy to understand for 8-12years old child

**Comment by kartikjoshi267** [comment]
I wish to work upon this issue. Can you please assign this issue to me under GSSOC'23?

**Comment by oshinsaraf** [comment]
Can you assign me this under GSSOC'23?

**Comment by gambhirsharma** [comment]
We already have a similar issue #124 

So, I am closing this issue.
