### ISSUE TITLE
fill them page UI can be more appealing

### ISSUE THREAD

**Issue by dc9deepika** [prakhartiwari0/Arito#161]
All in black and looking very boring. We can improvised it

**Comment by dev221b** [comment]
Could you please assign this to me? Being a GSSoC'23 Contributor, I am sure that I can enhance the overall user experience of the website

**Comment by gambhirsharma** [comment]
Hey, @dc9deepika do you want to work on this issue?

If yes then explain to us in detail how you will implement this feature and also provide some design prototypes. 

For now, I am temporarily closing this issue. If you want to work on this issue reopen it and start contributing.
