### ISSUE TITLE
Blog Of Mathematical Operations

### ISSUE THREAD

**Issue by swastika2108** [prakhartiwari0/Arito#162]
The feature isn't related to a problem but people may seek to know more about math's operators like **division by zero and multiplication tables addition tricks or Vedic maths.**

I want we should add a link of blog section about different mathematical operations so that people can refer to it like how to add, how to multiply, how to subtract, and how to divide and exception cases of division by 0!,We can give pictures of how to add and some interesting facts about math!We can even extend this site to have more mathematical expression like **powers, fractions, logarithm etc.**

We can either give the **solution of the problems** which a student did wrong!

**Comment by gambhirsharma** [comment]
Sorry, @swastika2108 we don't think we will ever add a blogging section to the website. It's a website for kids to practice/play with simple math problems like Addition/Subtraction. We don't think we need this feat.
