### ISSUE TITLE
Add Log In button enhancement

### ISSUE THREAD

**Issue by ShrutiSingh-1** [prakhartiwari0/Arito#165]
The is sign in with github button but no login button . So can add the feature in the project.

**Comment by ShrutiSingh-1** [comment]
please assign me this work!!
@prakhartiwari0

**Comment by ShrutiSingh-1** [comment]
@prakhartiwari0 Thankyou!!

**Comment by gambhirsharma** [comment]
This project doesn't use any backend so I don't think this issue makes any sense.
