### ISSUE TITLE
[IMPROVEMENT] Improving UI and adding a navbar

### ISSUE THREAD

**Issue by varsha-kadaru** [prakhartiwari0/Arito#166]
## What improvement are you suggesting?
Tell us what improvement(s) are you thinking about for this project.
The UI can be improved in all the pages and navbar can be added inorder to switch to different pages easily

## Why should make this improvement?
Adding this improvement makes the website attractive

## How can we make these improvements?
By adding extra CSS

## Additional Context
Write if you have anything more to say, or if you want to add screenshots, links, or videos.

**Comment by ravirt7911** [comment]
Hey @varsha-kadaru @prakhartiwari0 
I would like to take up this and add the navbar component according to the components present in the app.. which makes the ui  better and also when clicked on a particular navlink there will be smooth scrolling.
So please assign me this.
Thank You.

**Comment by gambhirsharma** [comment]
Also, I don't think this website requires a navbar bcoz it's a Maths challenge game for kids and there is nothing to add in the nav section.

I am closing this issue.
