### ISSUE TITLE
[IMPROVEMENT] Enhacing the Let's Start Page

### ISSUE THREAD

**Issue by Vishalk91-4** [prakhartiwari0/Arito#167]
## What improvement are you suggesting?
After Clicking the Let's start page we land on a page where we are required to fill up details but we cannot go back to home page from there, so I can add the logo there, so that it can be redirected back to the home page

In the top left section
![Screenshot 2023-05-27 164646](https://github.com/prakhartiwari0/Arito/assets/116670999/e2eba617-c5ed-4453-8a1d-e37b49dc09fe)

@prakhartiwari0 could you please assign it to me under GSSOC23

## Why should make this improvement?
To Resolve the problem of not being able to go back to home page

## How can we make these improvements?
Describe the process or the changes we should do to make these improvements

## Additional Context
Write if you have anything more to say, or if you want to add screenshots, links, or videos.

**Comment by gambhirsharma** [comment]
Duplicate issue. check #107
