### ISSUE TITLE
[FEATURE] Adding the Footer Section to the Website

### ISSUE THREAD

**Issue by Vishalk91-4** [prakhartiwari0/Arito#168]
**Is your feature request related to a problem? Please describe.**
There Should be footer section which would matc with the friendly UI, but will contain the Support the creator, contribute and all those sections

Putting all these in the footer section, so that they don't have to worry, like a maths student doesn't know about this, so keeping it at the last
![Screenshot 2023-05-27 164812](https://github.com/prakhartiwari0/Arito/assets/116670999/d7826099-2a14-4ebc-8cc1-8d0583946dba)

@prakhartiwari0 could you please assign it to me under GSSOC23

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Uzmakh** [comment]
I also want to work on it. Tell me if there's any possibility for me.

**Comment by gambhirsharma** [comment]
I don't think this website requires a footer bcoz it's a Maths challenge game for kids and there is nothing to add in the footer section.

I am closing this issue.
