### ISSUE TITLE
Scrollbar need some extra styling [FEATURE] 

### ISSUE THREAD

**Issue by HimanshuNarware** [prakhartiwari0/Arito#172]
**Is your feature request related to a problem? Please describe.**
I want to Add color gradient to the scrollbar btn  and also want to add some styling to it

**Describe the solution you'd like**
instead of using single color in scrollbar, I want to add two different colors of you web app in scrollbar it improve the UI of website

**Additional context**
##Screenshot
![58](https://github.com/prakhartiwari0/Arito/assets/83147410/39971bf0-5dc0-44f1-86f6-7b0ce1b49885)

**Comment by gambhirsharma** [comment]
Hey, @HimanshuNarware do you want to work on this issue?

If yes then explain to us in detail how you will implement this feature and also provide some design prototypes. 

For now, I am temporarily closing this issue. If you want to work on this issue reopen it and start contributing.

**Comment by HimanshuNarware** [comment]
@gambhirsharma  what think on this
![9](https://github.com/prakhartiwari0/Arito/assets/83147410/70a15cd7-fa24-4513-a793-95ca5a9d954a)

**Comment by HimanshuNarware** [comment]
@gambhirsharma  This is look more attractive and match with the theme of the weebsite more

**Comment by gambhirsharma** [comment]
I think it makes no sense to use a gradient in the scroll bar. Also, there might be a compatibility issue with another browser.
