### ISSUE TITLE
[IMPROVEMENT] 

### ISSUE THREAD

**Issue by dev221b** [prakhartiwari0/Arito#174]
## What improvement are you suggesting?
Improve the text font and overall display of the website

## Why should make this improvement?
More appealing website, easy to read and more comfortable to the eye

## How can we make these improvements?
Can make changes the stylesheet and the html pages

## Additional Context
If this issue is assigned to me, as a GSSoC'23 Contributor, I'll do my best in contributing to the overall user experience of the website.

**Comment by gambhirsharma** [comment]
Hey, @dev221b do you want to work on this issue?

If yes then explain to us in detail how you will implement this feature and also provide some design prototypes. 

For now, I am temporarily closing this issue. If you want to work on this issue reopen it and start contributing.
