### ISSUE TITLE
[IMPROVEMENT]: PAGESPEED INSIGHTS SCORE 

### ISSUE THREAD

**Issue by 0xabdulkhalid** [prakhartiwari0/Arito#177]
## What improvement are you suggesting?
- This issue about Pagespeed Insights Score, Scoring in these metrics are crucial to every web application so that it can have more advantages in terms of professional aspects
- So I gonna improve the `SEO` & `Accessibility` score for this Site, you can check out the below screenshot to get current score of this our Site

## Why should make this improvement?
- Without this improvement we can't gather audience from the Google search & more, even if you  don't have enough score then Google search will not even recommend our Site

## How can we make these improvements?
- I can able to make necessary changes in terms of both `Accessibility` & `SEO`, I'm one of the best when it comes to Optimizing sites with real world best practices so that our site could achieve more reach!

## Current Score

![Screenshot 2023-05-30 at 09-00-52 PageSpeed Insights](https://github.com/prakhartiwari0/Arito/assets/92252895/9a1e2cbc-968d-4803-845d-29f78a339e75)

## Postscript
- I'm a `GSSoC'23` contributor so kindly assign me to this issue with `GSSoC23` and `level 3` labels for improvements take further development.
- Regards!

**Comment by gambhirsharma** [comment]
Hey, @0xabdulkhalid the SEO part has been assigned to another contributor. You can work on the Performance or accessibility part.

I am assigning this issue to you.
