### ISSUE TITLE
Make ui of Arito better

### ISSUE THREAD

**Issue by Aliza30** [prakhartiwari0/Arito#178]
Make more interactive and responsive page for good user experience

**Comment by Aliza30** [comment]
i am unable to push the branch can u plz grant me permission to push the changes or is there any other problem.
<img width="685" alt="Screenshot 2023-06-02 at 1 48 08 AM" src="https://github.com/prakhartiwari0/Arito/assets/104764771/ae1675be-e747-44f7-a7cd-15bdc527dbd6">

**Comment by priyanshu942** [comment]
I'm a GSSoC contributor ..
I would like to work on this section...

would you please assign me to this task ??

**Comment by Aliza30** [comment]
> I'm a GSSoC contributor .. I would like to work on this section...
> 
> would you please assign me to this task ??

**Comment by gambhirsharma** [comment]
Hey, @Aliza30 do you want to work on this issue?

If yes then explain to us in detail how you will implement this feature and also provide some design prototypes. 

For now, I am temporarily closing this issue. If you want to work on this issue reopen it and start contributing.
