### ISSUE TITLE
[IMPROVEMENT] Adding a sticky navbar to the website [GSSoC'23]

### ISSUE THREAD

**Issue by 1Shubham7** [prakhartiwari0/Arito#179]
## What improvement are you suggesting?
I think the website would be better if we add a sticky navbar on the top.

## Why should make this improvement?
To make the website more fun and interesting and to increase ease of navigation for the users.

## How can we make these improvements?
I can code a navbar.

## Additional Context
Please assign me this issue under GSSoC'23

**Comment by 1Shubham7** [comment]
please assign me this issue under GSSoC'23

**Comment by gambhirsharma** [comment]
I don't think this website requires a navbar bcoz it's a Maths challenge game for kids and there is nothing to add in the navbar section.

I am closing this issue.
