### ISSUE TITLE
Additions in Issue Template

### ISSUE THREAD

**Issue by Anshika-Jain02** [prakhartiwari0/Arito#183]
## Description:

*I noticed that the repository does not have an appropriate issue template.*

*Issue Template: I want to add  some more points to your issue template like styling changes etc*

Please assign this issue to me under Gssoc'23 @prakhartiwari0

**Comment by gambhirsharma** [comment]
@Anshika-Jain02 can you provide more detail on what change/add you want to make in the issue template?

**Comment by gambhirsharma** [comment]
no response. I am closing this issue.
