### ISSUE TITLE
copy right footer 

### ISSUE THREAD

**Issue by Sushilverma002** [prakhartiwari0/Arito#184]
**Is your feature request related to a problem? Please describe.**
there is no copy right reserved footer.
**Describe the solution you'd like**
i would like to add on.
![Untitled](https://github.com/prakhartiwari0/Arito/assets/114687502/9ed27050-b8ac-4a9a-af30-8cf14f1ded89)
protect form copy right issue.
**Describe alternatives you've considered**

**Additional context**

**Comment by gambhirsharma** [comment]
I don't think this website requires a footer bcoz it's a Maths challenge game for kids and there is nothing to add in the footer section.

I am closing this issue.
