### ISSUE TITLE
[FEATURE]: Add "Leaderboard " Feature for Kids & Students

### ISSUE THREAD

**Issue by NarendraKoya999** [prakhartiwari0/Arito#189]
### How To Design that Feature ??

- Create **Leaderboard Section** , specially Appearing on **Whenever Particular Student submitted the Certain Task.**
- In **Leaderboard Section**, add Several Options namely **Candidate Name, Questions Type, Difficulty Level, Number of Questions Solved respectively.**
- **When the Difficulty Levels Increases Level by Level, gives One Star for Each Level based on Number of Questions Solved in Particular Section in Particular Subject.**
## Example:
- Suppose, **One Student Completed Very Easy Questions of Addition Subject and Out of 10 only solved 8 Questions and that Star filled with 80% yellow Color. Likewise, Maintained Leaderboard for Candidates.**

### Advantages:

- T**he advantage of this Feature is Improving the Level of Consistency and Questioning in Student Mindset like _Where I am in Particular Subject ??_  based on Difficulty of Questions with respective Subject Point of Way.**
- **Final outcome of this Feature is gives the More Confidence to Candidates and Encouraging the Talent.**

**Comment by gambhirsharma** [comment]
This website doesn't use any backend so it would not be possible to implement this type of feature. 

I am closing this issue.

**Comment by NarendraKoya999** [comment]
Ok. Thank You @gambhirsharma . I come up with Front End Ideas

**Comment by gambhirsharma** [comment]
> Ok. Thank You @gambhirsharma . I come up with Front End Ideas

you can open a new PR for your Front End Idea.
