### ISSUE TITLE
[BUG] Homepage Backgroud Music not playing

### ISSUE THREAD

**Issue by prakhartiwari0** [prakhartiwari0/Arito#19]
**Describe the bug**
I have tested and found that the background music which is supposed to be played automatically when we open the [homepage](https://arito.netlify.app/), is **NOT PLAYING.**
And this error in the console is coming -
![image](https://user-images.githubusercontent.com/65062036/202855210-5c33a95a-d794-4a8b-8ee2-51f9618af5ac.png)

```
Uncaught (in promise) DOMException: play() failed because the user didn't interact with the document first. https://goo.gl/xX8pDD
```
I did a little bit of research and found that [Autoplay with sound is allowed if the user has interacted with the domain  (click, tap, etc.).](https://developer.chrome.com/blog/autoplay/#new-behaviors). For more info read [Autoplay policy in Chrome](https://developer.chrome.com/blog/autoplay).

**To Reproduce**
1. Go to https://arito.netlify.app
2. Notice there is no background music being played (if it is played, it may be **due to extensions in your browser**)
3. Try to reproduce on a browser with no extensions or temporarily disable all the extensions.

**Expected behavior**
The background music should start playing automatically when the app is opened as shown in the [Demo Video](https://www.youtube.com/watch?v=4nkchB3KVyo).

**Screenshots**
Watch the [Demo Video](https://www.youtube.com/watch?v=4nkchB3KVyo) and see that the background music is playing, it was because of a live server extension in VS code. But the same thing is not happening in the app when there is no user interaction or extensions that could interact with the website.

**Desktop:**
 - Ubuntu
 - Brave Browser
 - v0.1

**Additional context**
This problem *may* get solved when we add the sound buttons functionality as explained in issue #13. We can keep the music muted by default, and when the user clicks on the buttons it will be an interaction and the music will start playing.

**Comment by prakhartiwari0** [comment]
> Hi @prakhartiwari0 on top of this issue I noticed that the background music volume that comes on while doing the exercises couldn't be turned down or muted.
> 
> Smartphone: Apple Browser: Safari

Hey, please open a new issue about this!
I wasn't aware of this one, thanks @EmmanuelEngelbert 😇

**Comment by EmmanuelEngelbert** [comment]
There also seems to be a bug on the same iPhone I was testing on concerning the missing sound after pressing the 'LET'S START!' button. The sound only comes on after pressing the 'GET SET GO!' button. Would you like me to attach this to the same issue? Thanks.

**Comment by prakhartiwari0** [comment]
Hey @EmmanuelEngelbert Sorry for the delayed reply, yes please make an issue for all of those problems that you are facing on apple devices and mention each detail properly.

Thanks for contributing 😇

**Comment by EmmanuelEngelbert** [comment]
Hi @prakhartiwari0,

No worries, thanks for giving me the chance to contribute!
I'll try my best to submit a legible issue when I get the time!
Many thanks!

**Comment by prakhartiwari0** [comment]
I don't think this issue is valid anymore
