### ISSUE TITLE
[FEATURE] ADDING A CONTACT US PAGE

### ISSUE THREAD

**Issue by kharshita590** [prakhartiwari0/Arito#190]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by tusharban42** [comment]
I'll be grateful if you could assign me the issue under GSSOC 23 !!!

**Comment by gambhirsharma** [comment]
I don't think this website requires a contact page bcoz it's a Maths challenge game for kids and there is nothing to add in the contact section.

I am closing this issue.
