### ISSUE TITLE
[FEATURE] :  footer 

### ISSUE THREAD

**Issue by pjyoti121** [prakhartiwari0/Arito#191]
I would like to create a footer for this website.
Please assign me this issue under gssoc'23

In footer i will add contact details and links of networking sites so that the parents of user can contact you

**Comment by tusharban42** [comment]
I would like to create a footer for this website.
Please assign me this issue under gssoc'23

**Comment by gambhirsharma** [comment]
I don't think this website requires a footer bcoz it's a Maths challenge game for kids and there is nothing to add in the footer section.

I am closing this issue.
