### ISSUE TITLE
[FEATURE]: Adding better font and font color.

### ISSUE THREAD

**Issue by bhavyasingh75** [prakhartiwari0/Arito#192]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is.
I really the idea of your website. However, one of my cousin is color-blind and she couldn't distinguish some of the colors used in the website.
**Describe the solution you'd like**
I would like to work on the color scheme of the website so that it becomes more accessible to young children and would look even better.

**Describe alternatives you've considered**
A clear and concise description of any alternative solutions or features you've considered. Using eye-friendly shades of colors.

**Additional context**

**Comment by gambhirsharma** [comment]
Hey, @bhavyasingh75 do you want to work on this issue?

If yes then explain to us in detail how you will implement this feature and also provide some design prototypes. 

For now, I am temporarily closing this issue. If you want to work on this issue reopen it and start contributing.
