### ISSUE TITLE
[GSSOC'23] --------[FEATURE] --Adding a "Back to Top" Button

### ISSUE THREAD

**Issue by VyjayantiN** [prakhartiwari0/Arito#193]
Is your feature request related to a problem? Please describe.
I often find myself scrolling down lengthy webpages, and it becomes inconvenient and time-consuming to manually scroll back to the top. This creates a frustrating user experience as it requires repetitive scrolling and makes it difficult to navigate back to the top of the page quickly.

Describe the solution you'd like
I would like to request the addition of a "Back to Top" button on webpages. This button should be prominently displayed and provide a convenient way for users to return to the top of the page with a single click. When clicked, it should smoothly scroll back to the top section of the webpage, enhancing user experience and reducing the effort required for navigation.

Describe alternatives you've considered

- Manually scrolling back to the top of the page using the scrollbar or touch gestures.
- Pressing the "Home" key on the keyboard to jump to the top of the page.
- Using browser extensions or plugins that provide a similar "Back to Top" functionality.
- While these alternatives exist, they may not provide the same level of convenience and ease of use as a dedicated "Back to Top" button.

**Comment by VyjayantiN** [comment]
Please assign me this issue under GSSOC'23.

**Comment by gambhirsharma** [comment]
There is already a PR working on this issue.
