### ISSUE TITLE
[GSSOC'23]-----[IMPROVEMENT] --Updating the home screen text of Arito to create  appealing introduction

### ISSUE THREAD

**Issue by VyjayantiN** [prakhartiwari0/Arito#194]
What improvement are you suggesting?
I suggest updating the home screen text of Arito to create a more engaging and appealing introduction to the WebApp.

Why should we make this improvement?
Making this improvement will have several positive outcomes. Firstly, it will attract more users, especially children, who are the primary target audience. By presenting Arito as the ultimate WebApp for sharpening arithmetic skills and emphasizing the joy and fun in math practice, we can create a strong appeal for users to explore and engage with the platform. This improvement will also enhance the overall user experience and increase user satisfaction, leading to higher user retention and potential growth of the user base.

How can we make these improvements?
To implement this improvement, we need to revise the existing home screen text with more compelling language and tone. We should highlight the key features and benefits of Arito, emphasizing its creative design and the joyful learning experience it offers. It's important to convey that Arito is not just for kids but can be used by anyone seeking to enhance their mathematical skills. By crafting a captivating and inspiring message, we can capture the attention and interest of our target audience.

This is the text which I wanted to add -----Introducing Arito, the ultimate WebApp for sharpening your arithmetic skills! Created with creativity and the aim of bringing joy to your learning experience, Arito is here to make math practice super fun. While it's perfect for kids who want to strengthen their mathematical abilities, anyone can join in on the excitement. Get ready to embark on a math-filled adventure that will leave you feeling confident and accomplished. Let's dive into the world of Arito and unlock your math superpowers

**Comment by VyjayantiN** [comment]
Please assign me this issue under GSSOC'23

**Comment by gambhirsharma** [comment]
Hey, @VyjayantiN do you want to work on this issue?

If yes then explain to us in detail how you will implement this feature and also provide some design prototypes. 

For now, I am temporarily closing this issue. If you want to work on this issue reopen it and start contributing.
