### ISSUE TITLE
[BUG] Images are not showing 

### ISSUE THREAD

**Issue by Anshul439** [prakhartiwari0/Arito#195]
**Describe the bug**
Images are not showing on main page

**Screenshots**

![Screenshot 2023-06-10 152159](https://github.com/prakhartiwari0/Arito/assets/123325132/a8b0e6c8-e9c8-499e-af4e-f469bf8d45b6)

Please assign this issue to me under GSSoC'23.

**Comment by gambhirsharma** [comment]
Can you provide more detail about the issue? 

Did you try refreshing the page? I think your internet connection caused this issue.

**Comment by gambhirsharma** [comment]
For now, I am temporarily closing this issue.
