### ISSUE TITLE
Adding the footer of the web page. 

### ISSUE THREAD

**Issue by devanshikapla** [prakhartiwari0/Arito#196]
I can add up the footer of the web page where I could add social media icons and can improve the overall UI of the project. In the footer I could add contact details in the footer of the web page. Please Assign this to me under GSSOC'23.

Thankyou!

**Comment by janhvii20** [comment]
can you please assign this issue to me

**Comment by gambhirsharma** [comment]
I don't think this website requires a footer bcoz it's a Maths challenge game for kids and there is nothing to add in the footer section.

I am closing this issue.
