### ISSUE TITLE
Adding Header  to make  it more attractive and systematic  

### ISSUE THREAD

**Issue by tamanna863** [prakhartiwari0/Arito#198]
Without Header  everything is looking quite distorted like    we have to scroll down again and again to  to see the topic  . If we add navbar for topics and link for heading it would be much more easier . 
We could do this via navbar and  anchor tags to to make it feasible . So we don't need to scroll back and forth , we could see the topics by just clicking link

**Comment by gambhirsharma** [comment]
I don't think this website requires a header bcoz it's a Maths challenge game for kids and there is nothing to add in the header section.

I am closing this issue.
