### ISSUE TITLE
[IMPROVEMENT] Improve the formatting and the overall ui of the project

### ISSUE THREAD

**Issue by ShreyaK11** [prakhartiwari0/Arito#199]
## What improvement are you suggesting?
Tell us what improvement(s) are you thinking about for this project.
I would like to improve the font size, colour, and background image and make the project more attractive and user-friendly.
Also, I will try to change the UI of the project to make it look more put together so that it attracts more users
I will improve this using html and CSS
I will change the font size.
Add headings to make the text easier to read and navigate
Also, I will improve the alignment of the project
Also, I will add make the background and overall project look attractive.

## Why should make this improvement?
Tell us the reasons why we should make these improvements, what will be the outcome?
I am making this improvement as I have noticed that the alignment of the text, and the overall look of the project can be improved.

## How can we make these improvements?
Describe the process or the changes we should do to make these improvements
I will improve this using html and CSS
I will change the font size.
Add headings to make the text easier to read and navigate
Also, I will improve the alignment of the project
Also, I will add make the background and overall project look attractive.

## Additional Context
Write if you have anything more to say, or if you want to add screenshots, links, or videos.

**Comment by gambhirsharma** [comment]
Hey, @ShreyaK11 do you want to work on this issue?

If yes then explain to us in detail how you will implement this feature and also provide some design prototypes. 

For now, I am temporarily closing this issue. If you want to work on this issue reopen it and start contributing.
