### ISSUE TITLE
[IMPROVEMENT]: Add All Media Queries At The Bottom Of The Stylesheet Page

### ISSUE THREAD

**Issue by NarendraKoya999** [prakhartiwari0/Arito#200]
GSSOC'23
## What improvement are you suggesting?
- In `main.css `File in Respective Project Directory .Particular Section having Some Design Properties and Values.
- In this Case, You can Added **media-queries** along with Particular Above Section. This happens in Other Sections Also.
- Suggest, Always Write **media-queries at the Bottom of the Web Page with adding Meaningful Comments to Each Section**.

## Why should make this improvement?
- **One Reason is, You Know that CSS will Pick up any of the style which are actually at the Bottom. It's going to take those styles as preference**.

## How can we make these improvements?
- **Put All our Media Queries in Bottom of The Particular File**.
- **Add Meaningful Comments about Media Queries with Respective Sections**.  

## Additional Context
- **Another Point about Designing Media Queries, If Page Stylesheet is Too Large and Having Huge Media Queries, Then Separate them into One Other File in Same Project Directory**.
- **Of Course, Most of the Developers and Programmers are Not Recommend This Approach.**

**Comment by gambhirsharma** [comment]
We don't think we need the changes mentioned above.
