### ISSUE TITLE
Arito

### ISSUE THREAD

**Issue by geekayushk** [prakhartiwari0/Arito#203]
Will make the template more responsive and will improve the UI.

<img width="887" alt="image" src="https://github.com/prakhartiwari0/Arito/assets/84330360/4a573cdc-9ce1-4478-b7f1-7e7338722d77">

**Comment by gambhirsharma** [comment]
Hey, @geekayushk do you want to work on this issue?

If yes then explain to us in detail how you will implement this feature and also provide some design prototypes. 

For now, I am temporarily closing this issue. If you want to work on this issue reopen it and start contributing.
