### ISSUE TITLE
[IMPROVEMENT] New UI of Arito

### ISSUE THREAD

**Issue by nihalpawar4** [prakhartiwari0/Arito#204]
## What improvement are you suggesting?
Tell us what improvement(s) are you thinking about for this project.

## Why should make this improvement?
Tell us the reasons why we should make these improvements, what will be the outcome?

## How can we make these improvements?
Describe the process or the changes we should do to make these improvements

## Additional Context
Write if you have anything more to say, or if you want to add screenshots, links, or videos.

**Comment by nihalpawar4** [comment]
hope this may work out .can you please assign me this issue

**Comment by gambhirsharma** [comment]
Hey, @nihalpawar4  do you want to work on this issue?

If yes then explain to us in detail how you will implement this feature and also provide some design prototypes. 

For now, I am temporarily closing this issue. If you want to work on this issue reopen it and start contributing.
