### ISSUE TITLE
Dark mode 

### ISSUE THREAD

**Issue by sk3316** [prakhartiwari0/Arito#206]
**Is your feature request related to a problem? Please describe.**
I love working on dark mode but the web app does not support dark mode which is a bit irritating for me and other developers too 

**Describe the solution you'd like**
Adding a dark mode switching option on the website will be beneficial for all users.

**Describe alternatives you've considered**
An alternative solution can be changing the color scheme to a somewhat darkish tone which can partially solve the problem

**Additional context**
"https://www.geeksforgeeks.org/how-to-create-dark-light-mode-for-website-using-javascript-jquery/"

**Comment by gambhirsharma** [comment]
We already have a similar issue #20 

So, I am closing this issue.
