### ISSUE TITLE
[BUG] :Audio is not working while playing the game.

### ISSUE THREAD

**Issue by lakshmiprasannakusumanchi** [prakhartiwari0/Arito#207]
**Describe the bug**
Audio is not working while playing the game.
**To Reproduce**
1. Go to 'main.html'
2. Click on 'get set go'
3. Click on 'start now'

**Expected behavior**
Audio should work while playing game

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by gambhirsharma** [comment]
This is a duplicate issue #48
