### ISSUE TITLE
[Improve]:  Improve the UI

### ISSUE THREAD

**Issue by dheeraj1129** [prakhartiwari0/Arito#208]
1. There's Hover effect in home page text which is not required.
2. No  menu button persent.
3. Improve nav bar.
4. Add some better colours.

**Comment by gambhirsharma** [comment]
Hey, @dheeraj1129 do you want to work on this issue?

If yes then explain to us in detail how you will implement this feature and also provide some design prototypes. 

For now, I am temporarily closing this issue. If you want to work on this issue reopen it and start contributing.
