### ISSUE TITLE
[FEATURE] Dark theme

### ISSUE THREAD

**Issue by MisterMickey** [prakhartiwari0/Arito#210]
**Is your feature request related to a problem? Please describe.**

I want to add an option for dark theme on landing page of website

![Screenshot from 2023-06-17 00-11-56](https://github.com/prakhartiwari0/Arito/assets/93720428/2359081c-d612-4fcb-9c08-f2a7076d0222)

**Comment by gambhirsharma** [comment]
We already have a similar issue #20 

I am closing this issue.
