### ISSUE TITLE
copy right footer

### ISSUE THREAD

**Issue by Sushilverma002** [prakhartiwari0/Arito#211]
**Is your feature request related to a problem? Please describe.**
no copy right footer
**Describe the solution you'd like**
it will protect the website for copy right
**Describe alternatives you've considered**

**Additional context**
![Untitled](https://github.com/prakhartiwari0/Arito/assets/114687502/5e0d9278-0e65-4f82-8020-1e1d7a3c58f5)

**Comment by prakhartiwari0** [comment]
We don't need a copyright text. It's an open-source project for kids. Also, there is not footer in the design of the app.

Happy Contributing!
