### ISSUE TITLE
Enhance footer part[IMPROVEMENT] 

### ISSUE THREAD

**Issue by Tusharjoshi1703** [prakhartiwari0/Arito#216]
## What improvement are you suggesting?
Tell us what improvement(s) are you thinking about for this project.

## Why should make this improvement?
Tell us the reasons why we should make these improvements, what will be the outcome?

## How can we make these improvements?
Describe the process or the changes we should do to make these improvements

## Additional Context
Write if you have anything more to say, or if you want to add screenshots, links, or videos.

**Comment by gambhirsharma** [comment]
I don't think this website requires a footer bcoz it's a Maths challenge game for kids and there is nothing to add in the footer section.

I am closing this issue.
