### ISSUE TITLE
can add more mathematical operation and functions, i.e., logarithm and exponent

### ISSUE THREAD

**Issue by shreyamaurya029** [prakhartiwari0/Arito#217]
We can add more mathematical functions like exponent and logarithm in the operations for  practice.
Then we can also make a miscellaneous section where students can practice all operations together.

**Comment by gambhirsharma** [comment]
@shreyamaurya029 this website is for kids of age less than 11 years. I don't think adding log and exponent will make any sense. You can open a new Discussion where you can talk with other contributors about it. Something similar to #6 

For now, I am closing this issue. You can reopen this issue after having a discussion with other contributors.
