### ISSUE TITLE
[FEATURE] footer style

### ISSUE THREAD

**Issue by devWonderkind** [prakhartiwari0/Arito#220]
**Is your feature request related to a problem? Please describe.**
improve footer

**Describe the solution you'd like**
i wanna improve footer
**Describe alternatives you've considered**

**Additional context**
preview
![add](https://github.com/prakhartiwari0/Arito/assets/110322061/398ae10a-6858-4aa2-bffd-4cb9b9e2337e)
 @prakhartiwari0 please assign me this issue under GSSoC'23

**Comment by gambhirsharma** [comment]
I don't think this website requires a footer bcoz it's a Maths challenge game for kids and there is nothing to add in the footer section.

I am closing this issue.
