### ISSUE TITLE
[IMPROVEMENT] Adding footer after Reviews & Reactions

### ISSUE THREAD

**Issue by Dimple-Choudhary** [prakhartiwari0/Arito#222]
## What improvement are you suggesting?
Adding a footer section after the "Reviews & Reactions" section.

## Why should make this improvement?
It's good to have a footer at the bottom when users want to connect with you they will directly scroll down.
Having a  footer at the bottom is good practice
## How can we make these improvements?
we will have the home page 1st then  Reviews & Reactions then the footer. If you would like we can add a footer on the pages where the quiz and result are.

## Additional Context
@prakhartiwari0  will you assign this issue to me under GSSoC'23?

**Comment by gambhirsharma** [comment]
I don't think this website requires a footer bcoz it's a Maths challenge game for kids and there is nothing to add in the footer section.

I am closing this issue.
