### ISSUE TITLE
[IMPROVEMENT] Adding a navbar at top and footer at the end

### ISSUE THREAD

**Issue by crapbagaah** [prakhartiwari0/Arito#223]
## What improvement are you suggesting?
A navbar at the top would be helpful to navigate around the website easily without having to search for it, also a footer after the review will make the website more presentable.

## Why should make this improvement?
User experience is quite an important behavior. To improve the user experience I am suggesting improvements so that users will visit the website more often.

## How can we make these improvements?
I would implement a navbar at the top for navigation through the website on what are the features available and it will easily be available by clicking the options on the navbar. The same goes for the footer. Instead of just scrolling it will direct the user to that particular section.

## Additional Context
I would like to work on this and I would like to get this issue assigned under GSSOC'23. Thank you.
![image](https://github.com/prakhartiwari0/Arito/assets/90127903/654e7277-387a-4f4c-9fd7-243009bd9f18)

**Comment by komalioruganti** [comment]
Can I work on this issue as well?

**Comment by nirajshaw23** [comment]
would like to add this feature ,do allow me .

**Comment by AMAN-BAGADIYA** [comment]
I am Aman Bagadiya and I would like to improve the user experience by creating navbars and footer. Can you please assign it to me! @crapbagaah 
Thank you.
Regards, 
Aman

**Comment by gambhirsharma** [comment]
I don't think this website requires a navbar or footer bcoz it's a Maths challenge game for kids and there is nothing to add in the navbar or footer section.

I am closing this issue.
