### ISSUE TITLE
[FEATURE] Add a challenge mode 

### ISSUE THREAD

**Issue by AnkitaBarbora** [prakhartiwari0/Arito#225]
**Is your feature request related to a problem? Please describe.**
Yes, the feature request is related to improving the user experience on the mathematical quiz website. Currently, the website lacks a time-based challenge mode and an option to skip questions, which can limit user engagement and frustrate players who encounter difficult or unfamiliar questions.

**Describe the solution you'd like**
I would like the addition of a challenge mode on the mathematical quiz website. This mode would require players to complete tasks within a specific time limit, adding an element of excitement and urgency to the gameplay. Users would be motivated to solve questions quickly and accurately, enhancing their mathematical skills under pressure.

Furthermore, I suggest implementing an option to skip questions. This feature would allow users to bypass questions they find challenging or don't know the answer to, providing a smoother and less frustrating experience. It would enable players to continue progressing through the quiz without getting stuck on a particular question.

**Additional context**
These features can attract a wider audience and encourage users to continue using the website to improve their mathematical abilities.

**Comment by AnkitaBarbora** [comment]
@prakhartiwari0 Please review this issue and assign it to me under GSSoC'23.

**Comment by gambhirsharma** [comment]
Can you explain to us in detail how you will implement this feature and also provide some design prototypes. 

I am assigning this issue to you but before you start coding, first explain in detail about the feature, then only we can allow you to raise a PR. Bcoz there are many issues that are working on similar features.

**Comment by AnkitaBarbora** [comment]
I want to Implement the challenge mode functionality by introducing a time limit for each question. Display the remaining time to the user, and when the time runs out, automatically move to the next question. And also Add a "Skip" button next to the answer options. When the user clicks on the skip button, move to the next question without validating their answer. I will use JavaScript to track the skipped questions and ensure they are not repeated.

The user can select the option for challenge mode here.
<img width="960" alt="Screenshot 2023-07-03 221617" src="https://github.com/prakhartiwari0/Arito/assets/101138526/43a0eea5-ce12-4af4-b1a4-7ceaed0d27ea">

And here is a rough demo of my idea. 
https://github.com/prakhartiwari0/Arito/assets/101138526/168e9326-1e74-414d-a863-ff27ddab05bf

Once I have your approval, I will proceed with coding and submit the PR for review. I am open to any further discussions or clarifications needed regarding this feature before proceeding.

Thank you for your attention, and I look forward to your response.

@gambhirsharma @prakhartiwari0
