### ISSUE TITLE
[FEATURE] Ability to navigate between questions

### ISSUE THREAD

**Issue by prakhartiwari0** [prakhartiwari0/Arito#24]
**Is your feature request related to a problem? Please describe.**
Sometimes we want to go to previous questions that we attempted, either to check our solution or maybe we moved to the next question by mistake, but there is no functionality for that.

**Describe the solution you'd like**
We can have two buttons, one on the top left and the other on the top right corner of our app, which can be used for navigation. The left one will navigate us to previous questions, and the right will be used to move to the question after the current one.

**Additional context**
A visual representation (just an example) of the buttons -
<img width="300px" src="https://static.vecteezy.com/system/resources/thumbnails/003/025/932/small/navigation-arrows-icons-set-free-vector.jpg">

**Comment by Teja36** [comment]
Hi there! Can I work on this please.

**Comment by prakhartiwari0** [comment]
> Hi there! Can I work on this please.

Sure! Go Ahead
