### ISSUE TITLE
Add some extra features

### ISSUE THREAD

**Issue by gangadhararaoande** [prakhartiwari0/Arito#251]
**Additional context**
I have just gone through your app, and it looks good and fabulous. I want to tell you something I have to share with you first of all you can add some more features like 
-> cube root
-> percent
-> square root
-> exponent and 
-> parentheses.
These features can save time and improve the sharpening of a student's brain while practicing.

Another thing is to add a dashboard-like button to showcase the person's data like how many tests were completed and how much time he/she took to complete the tests. And can add a feature like badges like (10% to 30%) (30% to 60%) (60% to 100%) give them a badge while achieving based on percentage.

When we are taking the test you can add the time right or left side to test the person how much time he/she is taking per question.

Looking forward to using the app with some other new features.

Thanks for the app,
Regards
Gangadhara Rao Ande

**Comment by prakhartiwari0** [comment]
This app is for kids under the age of 11-12, all these things aren't suitable for it. Maybe we can build another app for that age group too. Thanks for your suggestion.
