### ISSUE TITLE
[FEATURE] Add RETEST & NEW TEST Buttons

### ISSUE THREAD

**Issue by prakhartiwari0** [prakhartiwari0/Arito#27]
**Is your feature request related to a problem? Please describe.**
There is a dummy button added in the RESULTS PAGE in this PR #8. But as the name suggests, it is just a dummy RETEST button and not a working one, and therefore to avoid confusion it is written in the button to reload the website for giving the test again.

We should have the two buttons on the Results Page - **RETEST** & **NEW TEST**

**Describe the solution you'd like**
The difference between RETEST and NEW TEST button's functions-

| RETEST | NEW TEST |
| --- | --- |
| This button will **redirect the user to the START TEST** page, and all the details that the user entered will be preserved and used for the test again. The benefit of this will be that if the user wants to **give the SAME TEST with the SAME DETAILS again**, it becomes frustrating to fill out the form again and again. This button **prevents the frustration of filling in the same details again** in the TEST FORM. | This button will **redirect the user to the TEST FOR**M and they need to fill in the new details. It can also be the case that **the user doesn't want to give the same test with the same details, they may want to change something**, and this button can be used in those cases. 

**Describe alternatives you've considered**
We can have a good discussion on what to add and what not.

**Comment by pathapativamsi** [comment]
Hello, Can I pick this one if no one is working on it?

**Comment by prakhartiwari0** [comment]
> Hello, Can I pick this one if no one is working on it?

Sure go ahead @pathapativamsi !
Remember to take a look at the code and how it's functioning, previously a few people made the retest button to reload the page which was actually not solving the issue, make sure not to do that mistake again!

Happy Contributing! 😇

**Comment by prakhartiwari0** [comment]
Tell me when you feel you are ready to work on this issue, and I will assign you then

**Comment by tejas-raskar** [comment]
Hello, I would like to work on this issue. Is anyone assigned to it yet?

**Comment by aswin2108** [comment]
@prakhartiwari0 I think it's not solved yet! If you could assign me, I would give it a try!

**Comment by prakhartiwari0** [comment]
So many issues at once might not be a good idea, you can first complete the other two issues that are assigned to you and then try if you could do something about this one.
I will not assign anybody else till then without asking from you, so don't worry 😄

Happy Contributing!

**Comment by williamssam** [comment]
Hi @pathapativamsi Can I work on this issue if it's not solved yet

**Comment by prakhartiwari0** [comment]
> Hi @pathapativamsi Can I work on this issue if it's not solved yet

Yup Sam, you can work on this one! But do read the issue properly as one person before did the wrong thing (for ref read this https://github.com/prakhartiwari0/Arito/pull/43#issuecomment-1333148700)
If you are sure that you can solve this one, tell me and I will assign you this issue!

Happy Contributing!

**Comment by williamssam** [comment]
> > Hi @pathapativamsi Can I work on this issue if it's not solved yet
> 
> Yup Sam, you can work on this one! But do read the issue properly as one person before did the wrong thing (for ref read this [#43 (comment)](https://github.com/prakhartiwari0/Arito/pull/43#issuecomment-1333148700)) If you are sure that you can solve this one, tell me and I will assign you this issue!
> 
> Happy Contributing!

I believe I can solve this issue, you can assign it to me

**Comment by Somya-Singhal** [comment]
Hi @prakhartiwari0 
Is this issue still open to work on?

**Comment by prakhartiwari0** [comment]
Nope, this issue has been solved in #55. Thanks for pointing it out! @pathapativamsi
