### ISSUE TITLE
[Improvement] Improve the Readme.md

### ISSUE THREAD

**Issue by prakhartiwari0** [prakhartiwari0/Arito#3]
We can have the following improvements in the Readme file -
- Add latest Screenshots inside the table (Replace older ones if required)
- Add more details about the project
- Add a Contributors Section

Any more suggestions are welcome!

**Comment by Kasambx** [comment]
Hey can I work on this?

**Comment by prakhartiwari0** [comment]
> Hey can I work on this?

Sure!

**Comment by aswin2108** [comment]
@Kasambx Shall I take it on from here!?
@prakhartiwari0 I have some ideas on this (not typos). It would be great if you could assign me this!

**Comment by Kasambx** [comment]
Sure, that's fine by me.
