### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by Om245** [prakhartiwari0/Arito#39]
When we complete our work
there is restarts button which not work 
and always we want to restart
problem in that is when we checked f5(restart)
always come msg that change made is not save 

suggestions is that fix this
or make login page and give each one option for saving there work (Like in points)

add calculus in it

**Comment by prakhartiwari0** [comment]
Hey Om, thanks for raising this issue.

A few things you need to know-
- We are already working on the issue of retesting and restarting the test, kindly check this issue: #27 
- Talking about that message that comes when you try to close/reload the app. It is to prevent you from mistakenly closing the app or the test and losing your progress. We will work on saving the progress with some better methods in future updates.
- I haven't studied calculus yet, and I need to first understand its concepts, and then only I can make logic to generate questions for that. As of now, this app is focused on kids ages 8-11 who can practice basic maths here. But soon we will be adding more and more types of questions to cover a larger portion of students.
