### ISSUE TITLE
[BUG] Same numbers coming in the question

### ISSUE THREAD

**Issue by prakhartiwari0** [prakhartiwari0/Arito#40]
**Describe the bug**
I have noticed that when doing small-number questions, sometimes the same question is repeated.

**To Reproduce**
1. Go to Arito
2. Choose a Very Easy level
3. Start the test
4. Do this multiple times till you get any repeated question

**Expected behavior**
Every question should be unique for a genuine result to come

**Screenshots**
| [Recording](https://user-images.githubusercontent.com/65062036/204122703-00ab13ca-e27f-4b8f-9c6f-8dd94d82317b.mp4) |
| --- |
In the attached recording there are two repeated questions, 1+1 & 4+1.

**Desktop (please complete the following information):**
 - Ubuntu 
 - Brave Browser
 - Version v1.5.1

**Comment by HenrySabio** [comment]
I have a solution for this and will be submitting a PR for it! @prakhartiwari0

**Comment by animeshsgit** [comment]
Hey @prakhartiwari0  , I have gone through your requirement and also the comments on the [PR](https://github.com/prakhartiwari0/Arito/pull/44) 

What I understood from your requirement is that 
- you need a combination of two numbers (lets say UPPER , LOWER ) in which UPPER is **always required to be greater or equal to** than LOWER 
- and the range is in between **1-9** for both the numbers.

If I am correct with the above requirement,
As per my analysis we can have only 45 combinations 

How?
For the UPPER number let's say 9 it can have 9 LOWER numbers i.e. 9,8,7,6,5,4,3,2,1,
For the UPPER number let's say 8 it can have 8 LOWER numbers i.e. 8,7,6,5,4,3,2,1,
In similar manner for all, therefore we can have 9+8+7+6+5+4+3+2+1 = 45  total possible combinations

If you agree with my analysis please put a comment I have a logic prepared with me and can raise a PR after-words,
or If you have any suggestion please respond

P.S. This is my first ever interaction with open source contribution, so if I missed any part or anything so.. feel free to tell me

**Comment by prakhartiwari0** [comment]
Hey @animeshsgit, I wanna appreciate your participation and congratulate you on your first-ever interaction in an open-source project!🥳
 You have a great start and a pretty good mindset while contributing 🚀 ([Must-Have Mindset for Open Source](https://blog.heyprakhar.xyz/new-to-open-source-know-everything-you-need-to))
 
I will reply soon after doing some calculations, however, I must point out that you may be wrong in assuming that the range is from 0-9 (in your 2nd point), as the numbers increase as the difficulty level increases. (Or maybe I got you wrong! Maths is a little tough you know 😅so we are prone to do mistakes)
 
Whatever the case, I will take some time to go to the root of the problem, and find a way to solve it. Don't worry, you will be writing the logic after we discuss the correct solution to it. 😉 
 
 Happy Contributing, Take care 😊

**Comment by animeshsgit** [comment]
Hey @prakhartiwari0 

I can understand you might be equipped with other priority works,
but I would really appreciate if you can revert back on the discussed scenario and  we can proceed for the fix.

You know how it feels, when you know there is a bug around you and you can do a treatment but for some reason you can't proceed😂

**Comment by prakhartiwari0** [comment]
Hey @animeshsgit 
I am really sorry for my delay in replying further, I was actually waiting for a response from your end on the mistake in your calculation that I was pointing out, at the starting days of the talk, but then gradually I forgot about this issue and started improving other aspects of the App.

You could go ahead with the PR and then we could actually see if your solution is working for all types of questions or not.

Thanks for your time,
Happy Contributing!

**Comment by animeshsgit** [comment]
Hey @prakhartiwari0 

Sorry for miscommunication that happened.

I will proceed with the resolution, also is there an any other medium we can communicate which would be less time consuming and quick resolution of queries.

Thanks

**Comment by prakhartiwari0** [comment]
Hey @animeshsgit 

The thing is that we may talk anywhere else like Discord or Twitter, but the problem is that other contributors might get confused and not know what is the conversation going on for a particular issue or PR, and if they aren't able to see that, it is not a good thing. Because this is an open-source project, all the talks must be visible to other contributors.

However, you may DM me on Twitter to talk about things that are not really important to be known by everyone, like very small changes or other queries. I will give you my Discord ID on Twitter so that we can communicate there too.

**Comment by animeshsgit** [comment]
Hey @prakhartiwari0 

Oh okay, got your concern.
Alright then we can discuss here only

Thanks

**Comment by prakhartiwari0** [comment]
Hey @animeshsgit I want to share something

**Comment by prakhartiwari0** [comment]
I have found the solution, and things are a little complicated yet easy to understand if you have good grasp in JavaScript Programming Basics

**Comment by prakhartiwari0** [comment]
Hmm 🤔 This idea is interesting, generating all the questions in one go and storing them in an array. I don't know what bugs will get in front of us using this method, and I don't know if it is applicable or not. 
Because a lot of changes have been made on top of the current system of generating numbers, we should not disturb the main process rather create new ways to tackle this problem (which I figured after doing some maths)

**Comment by prakhartiwari0** [comment]
It is late night now (for me) I will be sharing elaborately what is my solution, and explain everything. It will reveal many hidden bugs that we were missing out and you will get to know some good little maths of the app! Exciting!

Take care, 
Happy Contributing!

**Comment by animeshsgit** [comment]
Great!
looking forward for your solution

Take care,

**Comment by prakhartiwari0** [comment]
Hey @animeshsgit I have solved this issue and have made some commits, if you want you can go through the changes to get an overview of what has happened. I assume that you may face some difficulty in understanding some code, as there is a mathematical formula to calculate the number of possibilities of the questions which you will not understand unless I explain it to you.

So I will be making a little documentation on how the whole program is working and how the calculations are happening, it will be short and easy to understand with images, so don't worry. You will get to know an example of solving a real-world development problem 😉

Will inform you after making it.
Take care, Happy Contributing!

**Comment by animeshsgit** [comment]
@prakhartiwari0 
It's really great that the additional issues also got resolved while dealing with the particular bug,
Looking forward for the documentation

Thanks
Take care, keep up the good work
