### ISSUE TITLE
Restrict user passing zero to the number of question input

### ISSUE THREAD

**Issue by williamssam** [prakhartiwari0/Arito#54]
## What improvement are you suggesting?
The number of questions input should not allow user to input 0.

## Why should we make this improvement?
Users can only add from 1 upwards in the input field adding zero gives the user unlimited question to solve 

## How can we make these improvements?
Describe the process or the changes we should do to make these improvements

## Additional Context
Write if you have anything more to say, or if you want to add screenshots, links, or videos.

**Comment by prakhartiwari0** [comment]
Would you like to work on this issue? @williamssam

**Comment by williamssam** [comment]
yes
