### ISSUE TITLE
[BUG] retest button is not working

### ISSUE THREAD

**Issue by lewisushindi** [prakhartiwari0/Arito#56]
user is not able to refresh the page automatically using the button. he/she has to reload the page manually

**Comment by lewisushindi** [comment]
I can fix the issue

**Comment by prakhartiwari0** [comment]
Hey @lewisushindi kindly check the existing issue before opening a new one, the issue you are raising is already raised here https://github.com/prakhartiwari0/Arito/issues/27 
Happy Contributing!
