### ISSUE TITLE
[IMPROVEMENT] Re-structuring and adding to the "Getting Your Changes Reviewed" section 

### ISSUE THREAD

**Issue by the-amazing-atharva** [prakhartiwari0/Arito#64]
## What improvement are you suggesting?
Adding a few lines in the "Getting Your Changes Reviewed" section and changing its format to a more easy-to-understand way.

## Why should make this improvement?
Easy for beginners to understand the process of post-contribution workflow

## How can we make these improvements?
I would like to be assigned to work on the contributions.md file and I would work on with basic markdown syntax

## Additional Context
Hey @prakhartiwari0, its me from the collaboration  🤝 channel

**Comment by vikaskumar2703** [comment]
is this issue open to add further improvements to contributing.md

**Comment by vikaskumar2703** [comment]
> is this issue open to add further improvements to contributing.md

similar issue exist to bring improvments to contributing.md
close this issue @the-amazing-atharva if work is complete

**Comment by prakhartiwari0** [comment]
@vikaskumar2703 Thanks for pointing this out, I am closing this issue now.
Happy Contributing!
