### ISSUE TITLE
4 answers out of 5 were correct but it says 3 out of 5 were correct

### ISSUE THREAD

**Issue by ehsaanChanga123** [prakhartiwari0/Arito#71]
![Screenshot (31)](https://user-images.githubusercontent.com/96651507/215285398-94a7d494-0220-4230-b81b-cfa533e6dd6b.png)
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by prakhartiwari0** [comment]
@ehsaanChanga123 Did you enable the negative marking? Please put up a recording of the complete test starting from the form

**Comment by prakhartiwari0** [comment]
@Saqibhussain596 Yeah you are right, and the person who raised the issues hasn't replied also. Thanks for pointing this out!
