### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by Dragon-stack** [prakhartiwari0/Arito#76]
**Describe the bug**
While addition I found if you try to put any alphabet as an answer you can actually put  alphabet 'E ' as an answer
it's an another thing whether it is right or wrong but , the issue here is the normal answer submission feature doesn't work and you answer will not get submitted.
Normally it should be submitted as an wrong answer but it is not getting submitted even by pressing enter multiple time .
**To Reproduce**
1. Go to addition
2. Click on E alphabet on your keyboard
3. Answer will be not submitted
4. No dialogue box or prompt for informing about this issue
5. Done button got jammed too

**Screenshots**

![Screenshot (1059)](https://user-images.githubusercontent.com/81705995/218461545-aa264f26-1cde-4fb0-82c3-5e9c650dbf8d.png)
@prakhartiwari0 
**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser Brave

**Comment by prakhartiwari0** [comment]
Hey @Dragon-stack , thanks for raising this issue. Actually, I should tell you that we are not supposed to allow non-number answers, like alphabets or signs, so it is a feature and not a bug. I hope I was able to explain.

**Comment by prakhartiwari0** [comment]
Happy Contributing!
