### ISSUE TITLE
[IMPROVEMENT] Music volume zero by default

### ISSUE THREAD

**Issue by sreevyshnavi02** [prakhartiwari0/Arito#78]
Improvement: The sound controls option in main.html is at the bottom of the page and requires the user to scroll down and search for the controls. It would be more user friendly to place the sound controls at the top of the page (preferably on top right)

As the music is automatically turned on when we land into main.html, it might be uncomfortable if the sound controls are placed somewhere below and are not readily available to turn off or reduce volume when the user is in a public place.

If this improvement is relevant, I would love to work on this issue

**Comment by sreevyshnavi02** [comment]
Here are the screen shots of the sound controls I was referring to.

<img width="929" alt="image" src="https://user-images.githubusercontent.com/75737654/219699577-f66a8b82-be57-4eb5-b68d-f221de933bbf.png">


<img width="570" alt="image" src="https://user-images.githubusercontent.com/75737654/219699370-326d806b-1422-4bb5-bb64-72d8c28ad046.png">

**Comment by vikaskumar2703** [comment]
are you suggestin to have a no music button instead of a volume-slider
also that havin a volume slider on the top right corner would look enormous and further not good in a mobile browser

**Comment by sreevyshnavi02** [comment]
I was suggesting this improvement only for desktop view, the volume slider might not be required in a mobile view.

For desktops volume controls aren't as accessible as in a smartphone. So, its good to make it easily accessible on the website, in my opinion.

**Comment by prakhartiwari0** [comment]
The issue is positioning, I am not sure if this can be implemented without leading to difficult bugs

**Comment by prakhartiwari0** [comment]
@sreevyshnavi02 You are making a good point that if the user is in a public place and the sound starts playing suddenly when the main game is started, it makes them irritated. Can we instead make the music volume zero when starting the app?

**Comment by prakhartiwari0** [comment]
Because the position of the volume slider is not a big one I think, but the sudden starting of music does ruin the experience. So making the music volume zero by default can be a good idea. What do you all think? @vikaskumar2703 @sreevyshnavi02

**Comment by sreevyshnavi02** [comment]
> Because the position of the volume slider is not a big one I think, but the sudden starting of music does ruin the experience. So making the music volume zero by default can be a good idea. What do you all think? @vikaskumar2703 @sreevyshnavi02 

Maybe we can just ask the user whether they want to enable sound before playing it. If that's done, we don't have change the position of the volume control.

**Comment by prakhartiwari0** [comment]
@sreevyshnavi02 
> Maybe we can just ask the user whether they want to enable sound before playing it. If that's done, we don't have change the position of the volume control.

Nope that will be unnecessary actually. Asking the user this small thing which doesn't even matter much is pretty senseless. I think keeping the audio muted / volume zero by default will be the best solution

**Comment by prakhartiwari0** [comment]
@sreevyshnavi02 Would you like to work on this issue? If yes, then please change the title of issue to "Volume Zero by default" and tell me if you want to get assigned for this.

**Comment by sreevyshnavi02** [comment]
@prakhartiwari0 
Yeah, I will work on it. You may assign to me.

**Comment by prakhartiwari0** [comment]
Sure Go Ahead!
