### ISSUE TITLE
[FEATURE]  BACK HOME BUTTON

### ISSUE THREAD

**Issue by bobbyy16** [prakhartiwari0/Arito#85]
There is no Home button on results page. 
Add a button to get back to home page.

**Comment by prakhartiwari0** [comment]
What do you mean by home page? @bobbyy16 
We have a new test button which makes a fresh form to start a new test, is the form page.

**Comment by bobbyy16** [comment]
I mean once you click "Let's Start", there is no way back to home page of your website, where all the info about your website located. my suggest add one more button somewhere apart from "retest" and "new test"

**Comment by Jiya55** [comment]
if this feature is implemented, could I be assigned for it?

**Comment by prakhartiwari0** [comment]
Oh got it @bobbyy16, thanks for raising this issue!

You didn't mention if you want to work on it and @Jiya55 has already asked, so I am assigning this to her. 

Happy Contributing!

**Comment by Jiya55** [comment]
Ok thanks. I will try my best to implement it (tho i can;t see myself assigned yet). But i might have a few questions on how to implement it as i just started learning Git and github and dont know much on how to contribute as i have mostly worked solo till now.

**Comment by bobbyy16** [comment]
you work on that issue and submit a pr, if that pr looks good he will merge

**Comment by Jiya55** [comment]
uhmm what is the fll form of pr in this case?

**Comment by Jiya55** [comment]
*full form

**Comment by Jiya55** [comment]
oh ok, i guess pr = pull request

**Comment by Jiya55** [comment]
i have added the back to home button. It is saying review required

**Comment by prakhartiwari0** [comment]
@Jiya55 I want you to read this article of mine and learn from the resources that are given in it - https://blog.heyprakhar.xyz/new-to-open-source-know-everything-you-need-to

Here's a good video about Basic Git & GitHub - https://www.youtube.com/watch?v=apGV9Kg7ics
Here's a complete guide for open source on Freecodecamp by Eddie (also linked in that blog) - https://www.youtube.com/watch?v=yzeVMecydCE

Take your time in learning and also apply these things in real life to learn better.

**Comment by prakhartiwari0** [comment]
> i have added the back to home button. It is saying review required

Yes I will review the changes and share the feedback, if it's not having any problems I will merge else you will need to make the changes, and the loop goes on until the changes are not having any issue...

**Comment by Jiya55** [comment]
uhmm i have already added the button and its approved too, so shouldnt this be closed?

**Comment by bobbyy16** [comment]
Yep!

**Comment by prakhartiwari0** [comment]
Oh yeah sorry for that @Jiya55 , and thanks @bobbyy16

**Comment by prakhartiwari0** [comment]
Happy Contributing!
