### ISSUE TITLE
[FEATURE] 

### ISSUE THREAD

**Issue by Kahono0** [prakhartiwari0/Arito#87]
I think name should persist i.e I should not need to fill in my name when taking a new test. Also volume should persist too.(In my opinion).
You can assign me this one :)

**Comment by prakhartiwari0** [comment]
Hey @Kahono0, thanks for this feature suggestion. Actually, a new test means that everything will reset to default and a completely new test will be started with new details and properties. So this feature is not really required according to me. If you have any more points to explain why it can be helpful then we can move forward, or else close this issue.

Happy Contributing!

**Comment by Kahono0** [comment]
Thank you @prakhartiwari0 for replying. Having to write a name for every new test seems to me like an unnecessary extra step.

**Comment by prakhartiwari0** [comment]
You have closed this issue so I think it's not much needed.
