### ISSUE TITLE
[FEATURE] : Dark and light theme option 

### ISSUE THREAD

**Issue by abhiraj-ku** [prakhartiwari0/Arito#88]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
A toggle button to change the site appearance from light to dark and vice -versa

**Describe alternatives you've considered**

**Additional context**

**Comment by prakhartiwari0** [comment]
#20 There is already an issue for this

**Comment by Tusharjoshi1703** [comment]
I can add a dark mode option by the help of toggle .Please assign it to me.
