### ISSUE TITLE
[BUG] Dropdown Menu is Out of the browser frame in small screen.

### ISSUE THREAD

**Issue by anikdhabal** [prakhartiwari0/Arito#92]
**Describe the bug**
Dropdown Menu is Out of the browser frame  in small screen.

**Expected behavior**
Menu should inside the frame.

**Screenshots**
<img width="374" alt="Screenshot 2023-03-27 221005" src="https://user-images.githubusercontent.com/81948346/228006714-e7a4d137-41ec-42b1-9741-c63066c72967.png">

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by RahulRana701** [comment]
hi @prakhartiwari0 I would like to work on this issue can you assign it to me..........

**Comment by prakhartiwari0** [comment]
@RahulRana701 I am not sure how this can be solved, or if this is even an issue or not. But if you can solve it then go ahead!

**Comment by RahulRana701** [comment]
hi @prakhartiwari0 the issue has already been solved , there is no problem in it...

**Comment by prakhartiwari0** [comment]
Oh, I didn't check. Thanks for informing @RahulRana701
