### ISSUE TITLE
Add Exit option to close the game .

### ISSUE THREAD

**Issue by Tusharjoshi1703** [prakhartiwari0/Arito#98]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
When the user is playing game ,an option of exit from the game should be used .
I'll create an option to close the game.

**Comment by prakhartiwari0** [comment]
Please edit your PR text to describe what exactly the issue is and how you think it can be solved @Tusharjoshi1703

**Comment by prakhartiwari0** [comment]
@Tusharjoshi1703 There is already an issue (#91 ) about that, please check existing issues before creating a new one.
